name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test-xcode-16:
    name: "Test Xcode 16.4"
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v5

      - name: Check cache for Swift dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --build-path PROJECT_DIR

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        if: github.event_name == 'pull_request'
        continue-on-error: true
        timeout-minutes: 10
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          exclude: Tests/**/*

  test-xcode-26:
    name: "Test Xcode 26.0.1"
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v5

      - name: Check cache for Swift dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --build-path PROJECT_DIR

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        if: github.event_name == 'pull_request'
        continue-on-error: true
        timeout-minutes: 10
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          exclude: Tests/**/*

  release-build:
    name: "Build in release mode"
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v5

      - name: Check cache for Swift dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build -c release