name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check cache for Swift dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-       

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --build-path PROJECT_DIR

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        continue-on-error: true
        timeout-minutes: 10
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          exclude: Tests/**/*